spring.application.name=todo
server.port=8081

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

#spring.datasource.url=jdbc:mysql://localhost:3306/todo_app
#spring.datasource.username=root
#spring.datasource.password=mysql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto = update



# Ubuntu/Linux sometimes requires this for file system permissions in /tmp
spring.datasource.url=jdbc:h2:mem:tododb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=suvarnam
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console Settings (Allows you to view the DB in your browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.globally_quoted_identifiers=true
#spring.h2.console.settings.trace=false
#spring.h2.console.settings.web-allow-others=true
#spring.sql.init.mode=always
#spring.mvc.pathmatch.matching-strategy=ant_path_matcher


